CREATE TYPE "public"."model_provider" AS ENUM('hf');--> statement-breakpoint
CREATE TYPE "public"."user_status" AS ENUM('active', 'inactive');--> statement-breakpoint
CREATE TABLE "telos-proxy_log" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid,
	"model_name" varchar(255),
	"request_hash" varchar(128),
	"prompt_truncated" text,
	"response_truncated" text,
	"latency_ms" integer,
	"cache_hit" boolean DEFAULT false NOT NULL,
	"status" varchar(64),
	"error_code" varchar(64),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "telos-proxy_model_config" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"provider" "model_provider" NOT NULL,
	"api_key_ref" text,
	"base_url" text,
	"model_name" varchar(255) NOT NULL,
	"defaults" jsonb DEFAULT '{}'::jsonb,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "telos-proxy_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "telos-proxy_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "telos-proxy_user" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"email" varchar(255) NOT NULL,
	"password_hash" text NOT NULL,
	"status" "user_status" DEFAULT 'active' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "telos-proxy_user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
ALTER TABLE "telos-proxy_log" ADD CONSTRAINT "telos-proxy_log_user_id_telos-proxy_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."telos-proxy_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "telos-proxy_model_config" ADD CONSTRAINT "telos-proxy_model_config_user_id_telos-proxy_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."telos-proxy_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "name_idx" ON "telos-proxy_post" USING btree ("name");